allowBuilds:
  core-js: set this to true or false
  ejs: set this to true or false
  gifsicle: set this to true or false
  hexo-util: set this to true or false
  highlight.js: set this to true or false
  jpegtran-bin: set this to true or false
  mozjpeg: set this to true or false
  optipng-bin: set this to true or false
  pngquant-bin: set this to true or false
  puppeteer: set this to true or false
onlyBuiltDependencies:
  - core-js
  - ejs
  - fsevents
  - gifsicle
  - hexo-util
  - highlight.js
  - jpegtran-bin
  - mozjpeg
  - optipng-bin
  - pngquant-bin
  - puppeteer
